# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wjy/lpgen_main/lpgen_main/lpgen-main220222

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wjy/lpgen_main/lpgen_main/lpgen-main220222

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wjy/lpgen_main/lpgen_main/lpgen-main220222/CMakeFiles /home/wjy/lpgen_main/lpgen_main/lpgen-main220222/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wjy/lpgen_main/lpgen_main/lpgen-main220222/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clutter

# Build rule for target.
clutter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clutter
.PHONY : clutter

# fast build rule for target.
clutter/fast:
	$(MAKE) -f CMakeFiles/clutter.dir/build.make CMakeFiles/clutter.dir/build
.PHONY : clutter/fast

#=============================================================================
# Target rules for targets named alt_decoder

# Build rule for target.
alt_decoder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alt_decoder
.PHONY : alt_decoder

# fast build rule for target.
alt_decoder/fast:
	$(MAKE) -f CMakeFiles/alt_decoder.dir/build.make CMakeFiles/alt_decoder.dir/build
.PHONY : alt_decoder/fast

#=============================================================================
# Target rules for targets named pllow

# Build rule for target.
pllow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pllow
.PHONY : pllow

# fast build rule for target.
pllow/fast:
	$(MAKE) -f CMakeFiles/pllow.dir/build.make CMakeFiles/pllow.dir/build
.PHONY : pllow/fast

#=============================================================================
# Target rules for targets named plwin

# Build rule for target.
plwin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plwin
.PHONY : plwin

# fast build rule for target.
plwin/fast:
	$(MAKE) -f CMakeFiles/plwin.dir/build.make CMakeFiles/plwin.dir/build
.PHONY : plwin/fast

alt_decoder.o: alt_decoder.c.o

.PHONY : alt_decoder.o

# target to build an object file
alt_decoder.c.o:
	$(MAKE) -f CMakeFiles/alt_decoder.dir/build.make CMakeFiles/alt_decoder.dir/alt_decoder.c.o
.PHONY : alt_decoder.c.o

alt_decoder.i: alt_decoder.c.i

.PHONY : alt_decoder.i

# target to preprocess a source file
alt_decoder.c.i:
	$(MAKE) -f CMakeFiles/alt_decoder.dir/build.make CMakeFiles/alt_decoder.dir/alt_decoder.c.i
.PHONY : alt_decoder.c.i

alt_decoder.s: alt_decoder.c.s

.PHONY : alt_decoder.s

# target to generate assembly for a file
alt_decoder.c.s:
	$(MAKE) -f CMakeFiles/alt_decoder.dir/build.make CMakeFiles/alt_decoder.dir/alt_decoder.c.s
.PHONY : alt_decoder.c.s

clutter.o: clutter.c.o

.PHONY : clutter.o

# target to build an object file
clutter.c.o:
	$(MAKE) -f CMakeFiles/clutter.dir/build.make CMakeFiles/clutter.dir/clutter.c.o
.PHONY : clutter.c.o

clutter.i: clutter.c.i

.PHONY : clutter.i

# target to preprocess a source file
clutter.c.i:
	$(MAKE) -f CMakeFiles/clutter.dir/build.make CMakeFiles/clutter.dir/clutter.c.i
.PHONY : clutter.c.i

clutter.s: clutter.c.s

.PHONY : clutter.s

# target to generate assembly for a file
clutter.c.s:
	$(MAKE) -f CMakeFiles/clutter.dir/build.make CMakeFiles/clutter.dir/clutter.c.s
.PHONY : clutter.c.s

get_tid.o: get_tid.c.o

.PHONY : get_tid.o

# target to build an object file
get_tid.c.o:
	$(MAKE) -f CMakeFiles/clutter.dir/build.make CMakeFiles/clutter.dir/get_tid.c.o
	$(MAKE) -f CMakeFiles/alt_decoder.dir/build.make CMakeFiles/alt_decoder.dir/get_tid.c.o
	$(MAKE) -f CMakeFiles/pllow.dir/build.make CMakeFiles/pllow.dir/get_tid.c.o
	$(MAKE) -f CMakeFiles/plwin.dir/build.make CMakeFiles/plwin.dir/get_tid.c.o
.PHONY : get_tid.c.o

get_tid.i: get_tid.c.i

.PHONY : get_tid.i

# target to preprocess a source file
get_tid.c.i:
	$(MAKE) -f CMakeFiles/clutter.dir/build.make CMakeFiles/clutter.dir/get_tid.c.i
	$(MAKE) -f CMakeFiles/alt_decoder.dir/build.make CMakeFiles/alt_decoder.dir/get_tid.c.i
	$(MAKE) -f CMakeFiles/pllow.dir/build.make CMakeFiles/pllow.dir/get_tid.c.i
	$(MAKE) -f CMakeFiles/plwin.dir/build.make CMakeFiles/plwin.dir/get_tid.c.i
.PHONY : get_tid.c.i

get_tid.s: get_tid.c.s

.PHONY : get_tid.s

# target to generate assembly for a file
get_tid.c.s:
	$(MAKE) -f CMakeFiles/clutter.dir/build.make CMakeFiles/clutter.dir/get_tid.c.s
	$(MAKE) -f CMakeFiles/alt_decoder.dir/build.make CMakeFiles/alt_decoder.dir/get_tid.c.s
	$(MAKE) -f CMakeFiles/pllow.dir/build.make CMakeFiles/pllow.dir/get_tid.c.s
	$(MAKE) -f CMakeFiles/plwin.dir/build.make CMakeFiles/plwin.dir/get_tid.c.s
.PHONY : get_tid.c.s

pllow.o: pllow.c.o

.PHONY : pllow.o

# target to build an object file
pllow.c.o:
	$(MAKE) -f CMakeFiles/pllow.dir/build.make CMakeFiles/pllow.dir/pllow.c.o
.PHONY : pllow.c.o

pllow.i: pllow.c.i

.PHONY : pllow.i

# target to preprocess a source file
pllow.c.i:
	$(MAKE) -f CMakeFiles/pllow.dir/build.make CMakeFiles/pllow.dir/pllow.c.i
.PHONY : pllow.c.i

pllow.s: pllow.c.s

.PHONY : pllow.s

# target to generate assembly for a file
pllow.c.s:
	$(MAKE) -f CMakeFiles/pllow.dir/build.make CMakeFiles/pllow.dir/pllow.c.s
.PHONY : pllow.c.s

plwin.o: plwin.c.o

.PHONY : plwin.o

# target to build an object file
plwin.c.o:
	$(MAKE) -f CMakeFiles/plwin.dir/build.make CMakeFiles/plwin.dir/plwin.c.o
.PHONY : plwin.c.o

plwin.i: plwin.c.i

.PHONY : plwin.i

# target to preprocess a source file
plwin.c.i:
	$(MAKE) -f CMakeFiles/plwin.dir/build.make CMakeFiles/plwin.dir/plwin.c.i
.PHONY : plwin.c.i

plwin.s: plwin.c.s

.PHONY : plwin.s

# target to generate assembly for a file
plwin.c.s:
	$(MAKE) -f CMakeFiles/plwin.dir/build.make CMakeFiles/plwin.dir/plwin.c.s
.PHONY : plwin.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... clutter"
	@echo "... rebuild_cache"
	@echo "... alt_decoder"
	@echo "... pllow"
	@echo "... plwin"
	@echo "... alt_decoder.o"
	@echo "... alt_decoder.i"
	@echo "... alt_decoder.s"
	@echo "... clutter.o"
	@echo "... clutter.i"
	@echo "... clutter.s"
	@echo "... get_tid.o"
	@echo "... get_tid.i"
	@echo "... get_tid.s"
	@echo "... pllow.o"
	@echo "... pllow.i"
	@echo "... pllow.s"
	@echo "... plwin.o"
	@echo "... plwin.i"
	@echo "... plwin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

